apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fy25acnssnflux
  namespace: default
spec:
  interval: 15m
  path: "./nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fy25acnssnflux